import type { ComposerModel } from './composer-model'

export type ComposerRuntimeTargetSelectionInput = Pick<
  ComposerModel,
  | 'actionableHostIds'
  | 'activeRepoId'
  | 'eligibleRepos'
  | 'hostOptions'
  | 'initialEphemeralVmRecipeId'
  | 'projectGroups'
  | 'projectHostSetups'
  | 'projects'
  | 'repoId'
  | 'repos'
  | 'selectedProjectGroup'
  | 'selectedProjectHostSetupOverrideId'
  | 'settings'
  | 'sshConnectionStates'
  | 'workspaceHostScope'
  | 'worktreesByRepo'
>

export type DerivedComposerStateInput = Pick<
  ComposerModel,
  | 'agentPrompt'
  | 'checkedHooksContextKey'
  | 'enableIssueAutomation'
  | 'hasLoadedIssueCommand'
  | 'issueCommandTemplate'
  | 'linkDebouncedQuery'
  | 'linkDirectItem'
  | 'linkItems'
  | 'linkedIssue'
  | 'linkedPR'
  | 'linkedWorkItem'
  | 'name'
  | 'repoId'
  | 'selectedRepo'
  | 'selectedRepoHookContextKey'
  | 'selectedRepoIsGit'
  | 'selectedRepoSlug'
  | 'setupDecision'
  | 'sparseDirectories'
  | 'sparseEnabled'
  | 'sparsePresetsByRepo'
  | 'sparseSelectedPresetId'
  | 'worktreesByRepo'
  | 'yamlHooks'
>
