export const MOBILE_RICH_MARKDOWN_EDITOR_BODY_PRIMARY = [
  ';',
  '      --font-mono: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", monospace;',
  '      --font-sans: Geist, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;',
  '    }',
  '    * { box-sizing: border-box; -webkit-tap-highlight-color: transparent; }',
  '    html, body {',
  '      width: 100%;',
  '      min-height: 100%;',
  '      margin: 0;',
  '      background: var(--editor-surface);',
  '      color: var(--foreground);',
  '      font-family: var(--font-sans);',
  '      overscroll-behavior: contain;',
  '    }',
  '    body { overflow: auto; }',
  '    #editor {',
  '      min-height: 100vh;',
  '      padding: 18px 16px 112px;',
  '      outline: none;',
  '      font-size: 14px;',
  '      line-height: 1.7;',
  '      word-wrap: break-word;',
  '      overflow-wrap: anywhere;',
  '      caret-color: var(--foreground);',
  '    }',
  '    #editor[contenteditable="false"] {',
  '      opacity: 0.78;',
  '    }',
  '    #editor:empty::before,',
  '    #editor p.is-empty:first-child::before {',
  '      content: attr(data-placeholder);',
  '      color: var(--muted-foreground);',
  '      pointer-events: none;',
  '    }',
  '    #editor > :first-child { margin-top: 0; }',
  '    h1, h2, h3, h4, h5, h6 {',
  '      margin: 1.5em 0 0.5em;',
  '      font-weight: 600;',
  '      line-height: 1.3;',
  '      letter-spacing: 0;',
  '    }',
  '    h1 { font-size: 1.85em; font-weight: 700; }',
  '    h2 { font-size: 1.4em; }',
  '    h3 { font-size: 1.15em; }',
  '    p, ul, ol, blockquote { margin: 0.75em 0; }',
  '    ul, ol { padding-left: 1.5em; }',
  '    ul { list-style: disc; }',
  '    ol { list-style: decimal; }',
  '    li { margin: 0.15em 0; }',
  '    li > p { margin: 0; }',
  '    ul[data-type="taskList"] {',
  '      padding-left: 0;',
  '      list-style: none;',
  '    }',
  '    ul[data-type="taskList"] > li {',
  '      display: flex;',
  '      align-items: flex-start;',
  '      gap: 6px;',
  '    }',
  '    ul[data-type="taskList"] > li > label {',
  '      flex-shrink: 0;',
  '      display: flex;',
  '      align-items: center;',
  '      height: 1.55em;',
  '      user-select: none;',
  '    }',
  '    ul[data-type="taskList"] input[type="checkbox"] {',
  '      appearance: none;',
  '      width: 16px;',
  '      height: 16px;',
  '      margin: 0;',
  '      border: 1.5px solid color-mix(in srgb, var(--foreground) 55%, transparent);',
  '      border-radius: 4px;',
  '      background: transparent;',
  '      position: relative;',
  '    }',
  '    ul[data-type="taskList"] input[type="checkbox"]:checked {',
  '      background: var(--primary);',
  '      border-color: var(--primary);',
  '    }',
  '    ul[data-type="taskList"] input[type="checkbox"]:checked::after {',
  '      content: "";',
  '      position: absolute;',
  '      left: 4px;',
  '      top: 1px;',
  '      width: 5px;',
  '      height: 9px;',
  '      border: solid var(--primary-foreground);',
  '      border-width: 0 2px 2px 0;',
  '      transform: rotate(45deg);',
  '    }',
  '    ul[data-type="taskList"] input[type="checkbox"]:disabled {',
  '      opacity: 0.65;',
  '    }',
  '    ul[data-type="taskList"] > li > div {',
  '      flex: 1;',
  '      min-width: 0;',
  '    }',
  '    ul[data-type="taskList"] > li[data-checked="true"] > div {',
  '      text-decoration: line-through;',
  '      color: var(--muted-foreground);',
  '    }',
  '    blockquote {',
  '      padding: 0.5em 1em;',
  '      border-left: 3px solid var(--border);',
  '      border-radius: 0 6px 6px 0;',
  '      color: var(--muted-foreground);',
  '      background: color-mix(in srgb, var(--foreground) 2%, transparent);',
  '    }',
  '    table {',
  '      width: 100%;',
  '      margin: 1em 0;',
  '      border-collapse: collapse;',
  '      font-size: 0.95em;',
  '    }',
  '    th, td {',
  '      padding: 8px 14px;',
  '      border: 1px solid var(--border);',
  '      text-align: left;',
  '      vertical-align: top;',
  '    }',
  '    th {',
  '      font-weight: 600;',
  '      background: color-mix(in srgb, var(--foreground) 4%, transparent);',
  '    }',
  '    tr:nth-child(odd) td {',
  '      background: color-mix(in srgb, var(--foreground) 1.5%, transparent);',
  '    }',
  '    code {',
  '      padding: 0.2em 0.4em;',
  '      border-radius: 5px;',
  '      background: color-mix(in srgb, var(--foreground) 8%, transparent);',
  '      font-size: 0.88em;',
  '      font-family: var(--font-mono);',
  '    }',
  '    pre {',
  '      margin: 0.75em 0;',
  '      padding: 14px 18px;',
  '      border-radius: 8px;',
  '      border: 1px solid color-mix(in srgb, var(--foreground) 6%, transparent);',
  '      overflow-x: auto;',
  '      line-height: 1.55;',
  '      background: color-mix(in srgb, var(--foreground) 6%, transparent);',
  '      font-family: var(--font-mono);',
  '      white-space: pre-wrap;',
  '    }',
  '    pre::before {',
  '      content: attr(data-language);',
  '      display: block;',
  '      min-height: 13px;',
  '      margin-bottom: 4px;',
  '      color: var(--muted-foreground);',
  '      font-size: 11px;',
  '      text-transform: uppercase;',
  '    }',
  '    pre code {',
  '      padding: 0;',
  '      border-radius: 0;',
  '      background: transparent;',
  '      font-size: 0.92em;',
  '      white-space: pre-wrap;',
  '    }',
  '    hr {',
  '      margin: 1.5em 0;',
  '      border: none;',
  '      border-top: 1px solid var(--border);',
  '    }',
  '    a {',
  '      color: var(--accent-link);',
  '      text-decoration: underline;',
  '      text-decoration-color: color-mix(in srgb, currentColor 40%, transparent);',
  '      text-underline-offset: 2px;',
  '    }',
  '    img {',
  '      display: block;',
  '      max-width: 100%;',
  '      margin: 0.75em 0;',
  '      border-radius: 8px;',
  '    }',
  '  </style>',
  '</head>',
  '<body>',
  '  <main id="editor" contenteditable="true" data-placeholder="Start writing..."></main>',
  '  <script>',
  '    (function () {',
  "      var editor = document.getElementById('editor');",
  "      var lastMarkdown = '';",
  '      var inputTimer = null;',
  '      var documentGeneration = 0;',
  '      var editable = true;',
  '      var suppressInput = false;',
  '',
  '      function post(message) {',
  '        window.ReactNativeWebView && window.ReactNativeWebView.postMessage(JSON.stringify(message));',
  '      }',
  '',
  '      function decodeMarkdownEntities(value) {',
  '        return String(value).replace(/&(#x[0-9a-f]+|#\\d+|amp|lt|gt|quot|apos);/gi, function (match, entity) {',
  '          var lower = String(entity).toLowerCase();',
  "          if (lower === 'amp') return '&';",
  "          if (lower === 'lt') return '<';",
  "          if (lower === 'gt') return '>';",
  "          if (lower === 'quot') return '\"';",
  "          if (lower === 'apos') return \"'\";",
  "          if (lower.indexOf('#x') === 0) {",
  '            var hex = Number.parseInt(lower.slice(2), 16);',
  '            return Number.isFinite(hex) && hex >= 0 && hex <= 0x10ffff ? String.fromCodePoint(hex) : match;',
  '          }',
  "          if (lower.indexOf('#') === 0) {",
  '            var code = Number.parseInt(lower.slice(1), 10);',
  '            return Number.isFinite(code) && code >= 0 && code <= 0x10ffff ? String.fromCodePoint(code) : match;',
  '          }',
  '          return match;',
  '        });',
  '      }',
  '',
  '      function escapeHtml(value) {',
  '        return decodeMarkdownEntities(value).replace(/[&<>"\']/g, function (char) {',
  "          return ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '\"': '&quot;', \"'\": '&#39;' })[char];",
  '        });',
  '      }',
  '',
  '      function escapeAttr(value) {',
  "        return escapeHtml(value).replace(/\\n/g, ' ');",
  '      }',
  '',
  '      function isSafeUrl(value) {',
  "        var trimmed = String(value || '').trim();",
  '        return !/^javascript:/i.test(trimmed);',
  '      }',
  '',
  '      function splitTableRow(line) {',
  "        return line.trim().replace(/^\\|/, '').replace(/\\|$/, '').split('|').map(function (cell) {",
  '          return cell.trim();',
  '        });',
  '      }',
  '',
  '      function isTableSeparator(line) {',
  '        var cells = splitTableRow(line);',
  '        return cells.length > 0 && cells.every(function (cell) {',
  '          return /^:?-{3,}:?$/.test(cell);',
  '        });',
  '      }',
  '',
  '      function renderInline(text) {',
  "        var output = '';",
  '        var pattern = /(!\\[[^\\]]*\\]\\([^)]+\\)|`[^`]+`|~~[^~]+~~|\\*\\*[^*]+\\*\\*|__[^_]+__|\\*[^*\\n]+\\*|_[^_\\n]+_|\\[[^\\]]+\\]\\([^)]+\\)|https?:\\/\\/[^\\s<]+)/g;',
  '        var lastIndex = 0;',
  '        var match;',
  '        while ((match = pattern.exec(text))) {',
  '          output += escapeHtml(text.slice(lastIndex, match.index));',
  '          var token = match[0];',
  '          var image = token.match(/^!\\[([^\\]]*)\\]\\(([^)]+)\\)$/);',
  '          var link = token.match(/^\\[([^\\]]+)\\]\\(([^)]+)\\)$/);',
  '          if (image && isSafeUrl(image[2])) {',
  "            output += '<img src=\"' + escapeAttr(image[2]) + '\" alt=\"' + escapeAttr(image[1] || '') + '\" />';",
  '          } else if (link && isSafeUrl(link[2])) {',
  "            output += '<a href=\"' + escapeAttr(link[2]) + '\">' + renderInline(link[1]) + '</a>';",
  '          } else if (/^https?:\\/\\//i.test(token)) {',
  "            output += '<a href=\"' + escapeAttr(token) + '\">' + escapeHtml(token) + '</a>';",
  "          } else if (token.indexOf('`') === 0) {",
  "            output += '<code>' + escapeHtml(token.slice(1, -1)) + '</code>';",
  "          } else if (token.indexOf('~~') === 0) {",
  "            output += '<s>' + renderInline(token.slice(2, -2)) + '</s>';",
  "          } else if (token.indexOf('**') === 0 || token.indexOf('__') === 0) {",
  "            output += '<strong>' + renderInline(token.slice(2, -2)) + '</strong>';",
  '          } else {',
  "            output += '<em>' + renderInline(token.slice(1, -1)) + '</em>';",
  '          }',
  '          lastIndex = pattern.lastIndex;',
  '        }',
  '        output += escapeHtml(text.slice(lastIndex));',
  '        return output;',
  '      }',
  '',
  '      function isBlockStart(line) {',
  '        return /^(```|#{1,6}\\s+|>\\s?|\\s*(?:[-*+]|\\d+[.)])\\s+|\\s*(-{3,}|\\*{3,}|_{3,})\\s*$)/.test(line);'
].join('\n')
