export const MOBILE_RICH_MARKDOWN_EDITOR_AFTER_KEYBOARD_DISMISS = [
  '',
  '      function runCommand(command) {',
  "        if (!editable || editor.getAttribute('contenteditable') !== 'true') return;",
  '        restoreSelectionOrEnd();',
  "        if (command === 'paragraph') document.execCommand('formatBlock', false, 'p');",
  "        else if (command === 'heading1') document.execCommand('formatBlock', false, 'h1');",
  "        else if (command === 'heading2') document.execCommand('formatBlock', false, 'h2');",
  "        else if (command === 'heading3') document.execCommand('formatBlock', false, 'h3');",
  "        else if (command === 'bold') document.execCommand('bold');",
  "        else if (command === 'italic') document.execCommand('italic');",
  "        else if (command === 'strike') document.execCommand('strikeThrough');",
  "        else if (command === 'bulletList') document.execCommand('insertUnorderedList');",
  "        else if (command === 'orderedList') document.execCommand('insertOrderedList');",
  "        else if (command === 'quote') document.execCommand('formatBlock', false, 'blockquote');",
  "        else if (command === 'inlineCode') wrapSelection('code');",
  "        else if (command === 'codeBlock') document.execCommand('insertHTML', false, '<pre data-language=\"\"><code>code</code></pre><p><br></p>');",
  '        else if (command === \'taskList\') document.execCommand(\'insertHTML\', false, \'<ul data-type="taskList"><li data-checked="false"><label contenteditable="false"><input type="checkbox" /></label><div><p>Task</p></div></li></ul>\');',
  "        else if (command === 'link') {",
  "          var href = window.prompt('Link URL');",
  "          if (href && isSafeUrl(href)) document.execCommand('createLink', false, href);",
  "        } else if (command === 'image') {",
  "          var src = window.prompt('Image URL');",
  "          if (src && isSafeUrl(src)) document.execCommand('insertImage', false, src);",
  '        }',
  '        syncTaskCheckboxesDisabled();',
  '        emitChange();',
  '      }',
  '',
  "      editor.addEventListener('input', function () {",
  '        selectionDroppedOnBlur = false;',
  '        if (editable) emitChange();',
  '      });',
  "      editor.addEventListener('change', function (event) {",
  '        var input = event.target && event.target.closest && event.target.closest(\'input[type="checkbox"]\');',
  '        if (input) {',
  '          if (!editable) {',
  '            event.preventDefault();',
  '            return;',
  '          }',
  "          var li = input.closest('li');",
  "          if (li) li.setAttribute('data-checked', input.checked ? 'true' : 'false');",
  '        }',
  '        if (editable) emitChange();',
  '      });',
  "      editor.addEventListener('click', function (event) {",
  "        var link = event.target && event.target.closest && event.target.closest('a[href]');",
  '        if (link) {',
  '          event.preventDefault();',
  "          post({ type: 'openLink', url: link.getAttribute('href') || '' });",
  '          return;',
  '        }',
  '        var input = event.target && event.target.closest && event.target.closest(\'input[type="checkbox"]\');',
  '        if (!input) {',
  '          if (!editable) return;',
  '          // Why: a task-list label forwards its click to the checkbox, so refocusing here would steal it and re-open the keyboard.',
  '          var uneditable = event.target && event.target.closest && event.target.closest(\'[contenteditable="false"]\');',
  '          if (uneditable && uneditable !== editor) return;',
  '          selectionDroppedOnBlur = false;',
  '          if (document.activeElement === editor) return;',
  '          // Why: refocusing after a dismissal otherwise types at the stale caret, not where the user tapped.',
  '          var caret = caretRangeAtPoint(event.clientX, event.clientY);',
  '          focusEditor();',
  '          if (caret && editor.contains(caret.commonAncestorContainer)) applySelectionRange(caret);',
  '          return;',
  '        }',
  '        if (!editable) {',
  '          event.preventDefault();',
  '          return;',
  '        }',
  "        var li = input.closest('li');",
  "        if (li) li.setAttribute('data-checked', input.checked ? 'true' : 'false');",
  '        emitChange();',
  '      });',
  "      editor.addEventListener('keydown', function (event) {",
  "        if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === 'b') {",
  '          event.preventDefault();',
  "          runCommand('bold');",
  '        }',
  '      });',
  '',
  '      window.__orcaRichMarkdown = { setMarkdown: setMarkdown, setEditable: setEditable, runCommand: runCommand, currentMarkdown: currentMarkdown, dismissKeyboard: dismissKeyboard };',
  ''
].join('\n')

export const MOBILE_RICH_MARKDOWN_EDITOR_DOCUMENT_END = [
  '',
  "      post({ type: 'ready' });",
  '    })();',
  '  </script>',
  '</body>',
  '</html>'
].join('\n')
