name: Other
description: Report another Orca issue type
title: '[Other]: '
body:
  - type: markdown
    attributes:
      value: |
        Please write your issue in English.

  - type: textarea
    id: details
    attributes:
      label: Details
      description: Share the context, request, or issue. Include a short summary here too.
    validations:
      required: true
