import { getRuntimeGitScope as getRuntimeGitScopeImplementation } from './runtime-git-client-context'
import {
  getRuntimeGitBranchCompare as getRuntimeGitBranchCompareImplementation,
  getRuntimeGitBranchDiff as getRuntimeGitBranchDiffImplementation,
  getRuntimeGitCommitCompare as getRuntimeGitCommitCompareImplementation,
  getRuntimeGitCommitDiff as getRuntimeGitCommitDiffImplementation,
  getRuntimeGitDiff as getRuntimeGitDiffImplementation
} from './runtime-git-diff-client'
import {
  cancelRuntimeGenerateCommitMessage as cancelRuntimeGenerateCommitMessageImplementation,
  cancelRuntimeGeneratePullRequestFields as cancelRuntimeGeneratePullRequestFieldsImplementation,
  discoverRuntimeCommitMessageModels as discoverRuntimeCommitMessageModelsImplementation,
  generateRuntimeCommitMessage as generateRuntimeCommitMessageImplementation,
  generateRuntimePullRequestFields as generateRuntimePullRequestFieldsImplementation
} from './runtime-git-generation-client'
import {
  getRuntimeGitConflictOperation as getRuntimeGitConflictOperationImplementation,
  getRuntimeGitHistory as getRuntimeGitHistoryImplementation,
  getRuntimeGitIgnoredPaths as getRuntimeGitIgnoredPathsImplementation,
  getRuntimeGitStatus as getRuntimeGitStatusImplementation,
  getRuntimeGitSubmoduleStatus as getRuntimeGitSubmoduleStatusImplementation,
  setRuntimeGitStatusUpstreamRefWatch as setRuntimeGitStatusUpstreamRefWatchImplementation
} from './runtime-git-status-client'
import {
  abortRuntimeGitMerge as abortRuntimeGitMergeImplementation,
  abortRuntimeGitRebase as abortRuntimeGitRebaseImplementation,
  commitRuntimeGit as commitRuntimeGitImplementation,
  fastForwardRuntimeGit as fastForwardRuntimeGitImplementation,
  fetchRuntimeGit as fetchRuntimeGitImplementation,
  getRuntimeGitUpstreamStatus as getRuntimeGitUpstreamStatusImplementation,
  pullRuntimeGit as pullRuntimeGitImplementation,
  pushRuntimeGit as pushRuntimeGitImplementation,
  rebaseRuntimeGitFromBase as rebaseRuntimeGitFromBaseImplementation,
  syncRuntimeGitForkDefaultBranch as syncRuntimeGitForkDefaultBranchImplementation
} from './runtime-git-sync-client'
import {
  bulkDiscardRuntimeGitPaths as bulkDiscardRuntimeGitPathsImplementation,
  bulkStageRuntimeGitPaths as bulkStageRuntimeGitPathsImplementation,
  bulkUnstageRuntimeGitPaths as bulkUnstageRuntimeGitPathsImplementation,
  discardRuntimeGitPath as discardRuntimeGitPathImplementation,
  getRuntimeGitRemoteCommitUrl as getRuntimeGitRemoteCommitUrlImplementation,
  getRuntimeGitRemoteFileUrl as getRuntimeGitRemoteFileUrlImplementation,
  stageRuntimeGitPath as stageRuntimeGitPathImplementation,
  unstageRuntimeGitPath as unstageRuntimeGitPathImplementation
} from './runtime-git-working-tree-client'

export type {
  RuntimeGenerateCommitMessageOverrides,
  RuntimeGenerateCommitMessageResult,
  RuntimeGeneratePullRequestFieldsOverrides,
  RuntimeGeneratePullRequestFieldsResult,
  RuntimeGitContext,
  RuntimePullRequestGenerationInput
} from './runtime-git-client-context'

export const getRuntimeGitScope = getRuntimeGitScopeImplementation
export const getRuntimeGitStatus = getRuntimeGitStatusImplementation
export const setRuntimeGitStatusUpstreamRefWatch = setRuntimeGitStatusUpstreamRefWatchImplementation
export const getRuntimeGitSubmoduleStatus = getRuntimeGitSubmoduleStatusImplementation
export const getRuntimeGitIgnoredPaths = getRuntimeGitIgnoredPathsImplementation
export const getRuntimeGitHistory = getRuntimeGitHistoryImplementation
export const getRuntimeGitConflictOperation = getRuntimeGitConflictOperationImplementation
export const abortRuntimeGitMerge = abortRuntimeGitMergeImplementation
export const abortRuntimeGitRebase = abortRuntimeGitRebaseImplementation
export const getRuntimeGitDiff = getRuntimeGitDiffImplementation
export const getRuntimeGitBranchCompare = getRuntimeGitBranchCompareImplementation
export const getRuntimeGitCommitCompare = getRuntimeGitCommitCompareImplementation
export const getRuntimeGitUpstreamStatus = getRuntimeGitUpstreamStatusImplementation
export const fetchRuntimeGit = fetchRuntimeGitImplementation
export const syncRuntimeGitForkDefaultBranch = syncRuntimeGitForkDefaultBranchImplementation
export const pullRuntimeGit = pullRuntimeGitImplementation
export const fastForwardRuntimeGit = fastForwardRuntimeGitImplementation
export const rebaseRuntimeGitFromBase = rebaseRuntimeGitFromBaseImplementation
export const pushRuntimeGit = pushRuntimeGitImplementation
export const getRuntimeGitBranchDiff = getRuntimeGitBranchDiffImplementation
export const getRuntimeGitCommitDiff = getRuntimeGitCommitDiffImplementation
export const commitRuntimeGit = commitRuntimeGitImplementation
export const generateRuntimeCommitMessage = generateRuntimeCommitMessageImplementation
export const discoverRuntimeCommitMessageModels = discoverRuntimeCommitMessageModelsImplementation
export const cancelRuntimeGenerateCommitMessage = cancelRuntimeGenerateCommitMessageImplementation
export const generateRuntimePullRequestFields = generateRuntimePullRequestFieldsImplementation
export const cancelRuntimeGeneratePullRequestFields =
  cancelRuntimeGeneratePullRequestFieldsImplementation
export const stageRuntimeGitPath = stageRuntimeGitPathImplementation
export const bulkStageRuntimeGitPaths = bulkStageRuntimeGitPathsImplementation
export const unstageRuntimeGitPath = unstageRuntimeGitPathImplementation
export const bulkUnstageRuntimeGitPaths = bulkUnstageRuntimeGitPathsImplementation
export const bulkDiscardRuntimeGitPaths = bulkDiscardRuntimeGitPathsImplementation
export const discardRuntimeGitPath = discardRuntimeGitPathImplementation
export const getRuntimeGitRemoteFileUrl = getRuntimeGitRemoteFileUrlImplementation
export const getRuntimeGitRemoteCommitUrl = getRuntimeGitRemoteCommitUrlImplementation
