import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import process from 'node:process'
import { afterEach, describe, expect, it } from 'vitest'
import { isFlattenedNodePtyLoaderMessage } from '../main/orcad/node-pty-loader-diagnosis'
import {
  collectNodePtyUnavailableDiagnosis,
  readNodeGypBuildRecord,
  surveyNodePtyBinding
} from './node-pty-binding-survey'
import { formatNodePtyUnavailableMessage } from './node-pty-unavailable-diagnosis'

const HOST = { platform: process.platform, arch: process.arch }
/** What node-pty throws once its loader has replaced the real cause with its last miss. */
const FLATTENED =
  'Failed to load native module: pty.node, checked: build/Release, build/Debug, ' +
  `prebuilds/${process.platform}-${process.arch}: Error: Cannot find module './pty.node'`

const roots: string[] = []

function fixture(options: { binding?: boolean; configGypi?: string } = {}): string {
  const root = mkdtempSync(join(tmpdir(), 'orca-node-pty-'))
  roots.push(root)
  const dir = join(root, 'node-pty')
  mkdirSync(join(dir, 'lib'), { recursive: true })
  writeFileSync(join(dir, 'lib', 'index.js'), 'module.exports = {}\n')
  writeFileSync(join(dir, 'lib', 'utils.js'), 'exports.loadNativeModule = () => ({})\n')
  if (options.binding) {
    mkdirSync(join(dir, 'build', 'Release'), { recursive: true })
    // Deliberately not a valid addon: the point is to make the dynamic loader talk.
    for (const name of ['pty.node', 'conpty.node']) {
      writeFileSync(join(dir, 'build', 'Release', name), 'not an addon\n')
    }
  }
  if (options.configGypi !== undefined) {
    mkdirSync(join(dir, 'build'), { recursive: true })
    writeFileSync(join(dir, 'build', 'config.gypi'), options.configGypi)
  }
  return dir
}

afterEach(() => {
  while (roots.length > 0) {
    rmSync(roots.pop()!, { recursive: true, force: true })
  }
})

describe('surveyNodePtyBinding', () => {
  it('finds the file node-pty itself would open, and lists where it looked when there is none', () => {
    const withBinding = surveyNodePtyBinding(fixture({ binding: true }), HOST)
    expect(withBinding?.bindingPath).toMatch(/build[/\\]Release[/\\](con)?pty\.node$/)

    const without = surveyNodePtyBinding(fixture(), HOST)
    expect(without?.bindingPath).toBeNull()
    expect(without?.searched).toHaveLength(3)
    expect(without?.searched.join(' ')).toContain(`prebuilds/${process.platform}-${process.arch}`)
  })
})

describe('readNodeGypBuildRecord', () => {
  it('reads what node-gyp configured for, past its leading comment lines', () => {
    const dir = fixture({
      configGypi:
        '# Do not edit. File was generated by node-gyp\'s "configure" step\n' +
        '{ "variables": { "node_module_version": 127, "target_arch": "arm64" } }\n'
    })
    expect(readNodeGypBuildRecord(dir)).toEqual({ nodeAbi: '127', arch: 'arm64' })
  })

  it('answers nothing rather than guessing when there is no build record', () => {
    expect(readNodeGypBuildRecord(fixture())).toEqual({ nodeAbi: null, arch: null })
  })
})

describe('collectNodePtyUnavailableDiagnosis', () => {
  it("recovers the dynamic loader's own words that node-pty threw away", async () => {
    // The whole defect in one assertion: what reaches the relay is FLATTENED, which names
    // no cause; the diagnosis must carry what the loader actually said about the file.
    const diagnosis = await collectNodePtyUnavailableDiagnosis({
      nodePtyDir: fixture({ binding: true }),
      error: new Error(FLATTENED)
    })
    expect(diagnosis.status).toBe('blocked')
    expect(diagnosis.rawError).toBeTruthy()
    expect(isFlattenedNodePtyLoaderMessage(diagnosis.rawError!)).toBe(false)
    expect(diagnosis.rawError).not.toBe(FLATTENED)
    expect(diagnosis.rawError).toMatch(/pty\.node/)
  }, 20_000)

  it("prefers node-gyp's build record over a loader message that named no fault", async () => {
    const diagnosis = await collectNodePtyUnavailableDiagnosis({
      nodePtyDir: fixture({
        binding: true,
        configGypi: '{ "variables": { "node_module_version": 4242, "target_arch": "x64" } }'
      }),
      error: new Error(FLATTENED)
    })
    // A garbage binary reads differently per platform (mach-o vs ELF), so only assert the
    // build record is consulted when the loader message did not name the fault itself.
    if (diagnosis.reason === 'abi_mismatch') {
      expect(formatNodePtyUnavailableMessage(diagnosis)).toContain(
        `built for Node ABI 4242, this host runs ABI ${process.versions.modules}`
      )
    } else {
      expect(['arch_mismatch', 'load_failed', 'load_crashed']).toContain(diagnosis.reason)
    }
  }, 20_000)

  it('reports an unlocatable install as unverifiable, not as a diagnosis', async () => {
    const diagnosis = await collectNodePtyUnavailableDiagnosis({
      nodePtyDir: null,
      error: new Error(FLATTENED)
    })
    expect(diagnosis.status).toBe('unverifiable')
    const text = formatNodePtyUnavailableMessage(diagnosis)
    expect(text).toContain('could not establish why')
    // It still has to be reportable: the raw error is the only thing an issue can quote.
    expect(text).toContain(FLATTENED)
  })

  it('probes the host toolchain only when nothing was compiled', async () => {
    const diagnosis = await collectNodePtyUnavailableDiagnosis({
      nodePtyDir: fixture(),
      error: new Error(FLATTENED)
    })
    expect(diagnosis.survey?.bindingPath).toBeNull()
    expect(['toolchain_missing', 'dependency_missing']).toContain(diagnosis.reason)
    // Non-Linux hosts ship a node-pty prebuild, so a toolchain answer there would be noise.
    expect(diagnosis.toolchain === null).toBe(process.platform !== 'linux')

    const compiled = await collectNodePtyUnavailableDiagnosis({
      nodePtyDir: fixture({ binding: true }),
      error: new Error(FLATTENED)
    })
    expect(compiled.toolchain).toBeNull()
  }, 20_000)
})
