import {
  AGENT_SESSION_BOUNDARY_RUNTIME_CAPABILITY,
  AUTOMATION_OWNER_FENCING_RUNTIME_CAPABILITY,
  SESSION_TAB_CLOSE_INTENT_RUNTIME_CAPABILITY,
  SESSION_TABS_AUTHORITATIVE_INVENTORY_RUNTIME_CAPABILITY,
  WORKTREE_VISIBILITY_DEFAULTS_RUNTIME_CAPABILITY,
  WORKTREE_VISIBILITY_SOURCE_DEFAULTS_RUNTIME_CAPABILITY,
  type RuntimeCapability
} from './protocol-version'
import { SKILL_INSTALL_RESULT_V2_CAPABILITY } from './skill-install-capability'

// Keep every remote request transport on the same mixed-version capability contract.
export function remoteRuntimeClientCapabilities(
  additionalCapabilities: readonly RuntimeCapability[] = []
): RuntimeCapability[] {
  return Array.from(
    new Set([
      SESSION_TAB_CLOSE_INTENT_RUNTIME_CAPABILITY,
      SESSION_TABS_AUTHORITATIVE_INVENTORY_RUNTIME_CAPABILITY,
      AGENT_SESSION_BOUNDARY_RUNTIME_CAPABILITY,
      SKILL_INSTALL_RESULT_V2_CAPABILITY,
      WORKTREE_VISIBILITY_DEFAULTS_RUNTIME_CAPABILITY,
      WORKTREE_VISIBILITY_SOURCE_DEFAULTS_RUNTIME_CAPABILITY,
      AUTOMATION_OWNER_FENCING_RUNTIME_CAPABILITY,
      ...additionalCapabilities
    ])
  )
}
