import { quotePosixShell } from '../../shared/wsl-login-shell-command'

export const WSL_SESSION_BRIDGE_TIMEOUT_MS = 30_000

const WSL_CODEX_SESSION_BRIDGE_BODY = [
  'set -u',
  'rollback_manifest=${3-}',
  'rollback_stage_root=${4-}',
  'scan_scope=${5-full}',
  'scan_start=${6-}',
  'scan_end=${7-}',
  'if [ -n "$rollback_manifest" ]; then',
  '  [ -n "$rollback_stage_root" ] || exit 1',
  '  mkdir -p -- "$rollback_stage_root" || exit 1',
  '  : > "$rollback_manifest" || exit 1',
  'fi',
  'scanned_files=0',
  'linked_files=0',
  'bridge_failed=0',
  'if [ ! -d "$source_sessions_root" ]; then',
  `  printf '{"scannedFiles":0,"linkedFiles":0}\\n'`,
  '  exit 0',
  'fi',
  'file_list=$(mktemp) || exit 1',
  'day_list="$file_list.days"',
  'trap \'rm -f -- "$file_list" "$day_list"\' EXIT HUP INT TERM',
  'case "$scan_scope" in',
  `  full) find "$source_sessions_root" -type f -name '*.jsonl' -print0 > "$file_list" || exit 1 ;;`,
  '  recent)',
  '    case "$scan_start" in ????/??/??) ;; *) exit 1 ;; esac',
  '    case "$scan_end" in ????/??/??) ;; *) exit 1 ;; esac',
  '    if [[ "$scan_start" > "$scan_end" ]]; then',
  `      find "$source_sessions_root" -type f -name '*.jsonl' -print0 > "$file_list" || exit 1`,
  '    else',
  '      : > "$file_list" || exit 1',
  '      find "$source_sessions_root" -mindepth 3 -maxdepth 3 -type d -print0 > "$day_list" || exit 1',
  "      while IFS= read -r -d '' session_day_root; do",
  '        session_day=${session_day_root#"$source_sessions_root"/}',
  '        case "$session_day" in ????/??/??) ;; *) continue ;; esac',
  '        [[ "$session_day" < "$scan_start" ]] && continue',
  '        find "$session_day_root" -maxdepth 1 -type f -name \'*.jsonl\' -print0 >> "$file_list" || exit 1',
  '      done < "$day_list"',
  '    fi',
  '    ;;',
  '  *) exit 1 ;;',
  'esac',
  "while IFS= read -r -d '' source_file; do",
  '  scanned_files=$((scanned_files + 1))',
  '  relative_path=${source_file#"$source_sessions_root"/}',
  '  target_file="$managed_sessions_root/$relative_path"',
  '  if [ -e "$target_file" ] || [ -L "$target_file" ]; then',
  '    continue',
  '  fi',
  '  target_dir=${target_file%/*}',
  '  if ! mkdir -p -- "$target_dir"; then',
  '    bridge_failed=1',
  '    continue',
  '  fi',
  '  link_source="$source_file"',
  '  if [ -n "$rollback_manifest" ]; then',
  '    staged_file="$rollback_stage_root/$relative_path"',
  '    staged_dir=${staged_file%/*}',
  '    if ! mkdir -p -- "$staged_dir" || ! ln -- "$source_file" "$staged_file"; then',
  '      bridge_failed=1',
  '      continue',
  '    fi',
  '    target_stage="$target_file.orca-bridge-$$"',
  '    if [ -e "$target_stage" ] || [ -L "$target_stage" ]; then',
  '      bridge_failed=1',
  '      continue',
  '    fi',
  '    if ! ln -- "$staged_file" "$target_stage"; then',
  '      if ! cp -- "$staged_file" "$target_stage" || ! cmp -s -- "$staged_file" "$target_stage"; then',
  '        rm -f -- "$target_stage"',
  '        bridge_failed=1',
  '        continue',
  '      fi',
  '    fi',
  '    if ! printf \'%s\\0%s\\0\' "$target_stage" "$target_file" >> "$rollback_manifest"; then',
  '      rm -f -- "$target_stage"',
  '      bridge_failed=1',
  '      continue',
  '    fi',
  '    link_source="$target_stage"',
  '  fi',
  // Codex resume ignores symlinked JSONL, so create links inside the distro.
  '  if ln -- "$link_source" "$target_file"; then',
  '    linked_files=$((linked_files + 1))',
  '  elif [ ! -e "$target_file" ] && [ ! -L "$target_file" ]; then',
  '    if [ -n "$rollback_manifest" ]; then',
  '      bridge_failed=1',
  '    else',
  '      target_stage="$target_file.orca-bridge-$$"',
  '      if [ ! -e "$target_stage" ] && [ ! -L "$target_stage" ] && cp -- "$source_file" "$target_stage" && cmp -s -- "$source_file" "$target_stage" && ln -- "$target_stage" "$target_file"; then',
  '        linked_files=$((linked_files + 1))',
  '      else',
  '        bridge_failed=1',
  '      fi',
  '      rm -f -- "$target_stage"',
  '    fi',
  '  fi',
  'done < "$file_list"',
  '[ "$bridge_failed" = 0 ] || exit 1',
  `printf '{"scannedFiles":%s,"linkedFiles":%s}\\n' "$scanned_files" "$linked_files"`
].join('\n')

export const WSL_CODEX_SESSION_BRIDGE_SCRIPT = [
  'source_sessions_root="$1"',
  'managed_sessions_root="$2"',
  WSL_CODEX_SESSION_BRIDGE_BODY
].join('\n')

export function buildWslCodexSessionBridgeShellCommand(paths: {
  managedSessionsRoot: string
  systemSessionsRoot: string
}): string {
  return [
    `source_sessions_root=${quotePosixShell(paths.systemSessionsRoot)}`,
    `managed_sessions_root=${quotePosixShell(paths.managedSessionsRoot)}`,
    WSL_CODEX_SESSION_BRIDGE_BODY
  ].join('\n')
}
