import { useEffect, type Dispatch, type RefObject, type SetStateAction } from 'react'
import { cancelRuntimeGeneratePullRequestFields } from '@/runtime/runtime-git-client'
import type { HostedReviewCreationEligibility } from '../../../../shared/hosted-review'
import type { SourceControlAiPrCreationDefaults } from '../../../../shared/source-control-ai-types'
import type {
  PullRequestFieldName,
  PullRequestFieldRevisions
} from '@/store/slices/pull-request-generation'
import { resolveCreateReviewDraftTitle } from './create-review-draft-title'
import { stripBaseRef } from './create-pull-request-base-ref-normalization'
import {
  createInitialPullRequestFieldRevisions,
  type GenerationSeed,
  type UseCreatePullRequestDialogFieldsOptions
} from './create-pull-request-dialog-field-model'

type CreatePullRequestFieldSeedingOptions = {
  open: boolean
  repoId: string
  worktreeId: string | null
  worktreePath: string
  branch: string
  eligibility: HostedReviewCreationEligibility | null
  hasExternalGeneration: boolean
  retainDraftWhenClosed: boolean
  currentEligibilityKey: string | null
  resolvedDefaultBaseRef: string
  resolvedPrDefaults: Required<SourceControlAiPrCreationDefaults>
  generation: UseCreatePullRequestDialogFieldsOptions['generation']
  markFieldDirty: (field: PullRequestFieldName) => void
  initializedFromEligibilityRef: RefObject<string | null>
  syncedDefaultBaseRef: RefObject<string | null>
  baseEditedByUserRef: RefObject<boolean>
  autoGeneratedForKeyRef: RefObject<string | null>
  generateInFlightRef: RefObject<boolean>
  generationRequestIdRef: RefObject<number>
  generationSeedRef: RefObject<GenerationSeed | null>
  restoredExternalGenerationSeedRef: RefObject<string | null>
  fieldRevisionsRef: RefObject<PullRequestFieldRevisions>
  setInitializedEligibilityKey: Dispatch<SetStateAction<string | null>>
  setBase: Dispatch<SetStateAction<string>>
  setTitle: Dispatch<SetStateAction<string>>
  setBody: Dispatch<SetStateAction<string>>
  setDraft: Dispatch<SetStateAction<boolean>>
  setBaseQuery: Dispatch<SetStateAction<string>>
  setBaseResults: Dispatch<SetStateAction<string[]>>
  setBaseSearchError: Dispatch<SetStateAction<string | null>>
  setGenerating: Dispatch<SetStateAction<boolean>>
  setGenerateError: Dispatch<SetStateAction<string | null>>
}

export function useCreatePullRequestFieldSeeding({
  open,
  repoId,
  worktreeId,
  worktreePath,
  branch,
  eligibility,
  hasExternalGeneration,
  retainDraftWhenClosed,
  currentEligibilityKey,
  resolvedDefaultBaseRef,
  resolvedPrDefaults,
  generation,
  markFieldDirty,
  initializedFromEligibilityRef,
  syncedDefaultBaseRef,
  baseEditedByUserRef,
  autoGeneratedForKeyRef,
  generateInFlightRef,
  generationRequestIdRef,
  generationSeedRef,
  restoredExternalGenerationSeedRef,
  fieldRevisionsRef,
  setInitializedEligibilityKey,
  setBase,
  setTitle,
  setBody,
  setDraft,
  setBaseQuery,
  setBaseResults,
  setBaseSearchError,
  setGenerating,
  setGenerateError
}: CreatePullRequestFieldSeedingOptions): void {
  useEffect(() => {
    if (!open) {
      if (!hasExternalGeneration) {
        generationRequestIdRef.current += 1
        if (generateInFlightRef.current) {
          const requestContext = generationSeedRef.current?.context
          if (requestContext?.worktreePath) {
            void cancelRuntimeGeneratePullRequestFields(requestContext)
          }
        }
        generateInFlightRef.current = false
        // Why: retain the draft + init marker across a temporary policy hide so a
        // hard-error recovery reopening the same context does not reseed and wipe
        // edits. A genuine context change still reseeds (the eligibility key on
        // reopen differs from the retained marker).
        if (!retainDraftWhenClosed) {
          generationSeedRef.current = null
          initializedFromEligibilityRef.current = null
          syncedDefaultBaseRef.current = null
          baseEditedByUserRef.current = false
          setInitializedEligibilityKey(null)
          autoGeneratedForKeyRef.current = null
        }
        setGenerating(false)
        setGenerateError(null)
      }
      return
    }
    if (!eligibility) {
      return
    }
    const initializationKey = currentEligibilityKey
    if (!initializationKey) {
      return
    }
    if (initializedFromEligibilityRef.current === initializationKey) {
      setInitializedEligibilityKey((current) =>
        current === initializationKey ? current : initializationKey
      )
      return
    }
    if (!hasExternalGeneration) {
      // Why: a branch/context switch invalidates any local AI request; cancel
      // it before reseeding fields so stale generated text cannot land later.
      generationRequestIdRef.current += 1
      const requestContext = generationSeedRef.current?.context
      if (generateInFlightRef.current && requestContext?.worktreePath) {
        void cancelRuntimeGeneratePullRequestFields(requestContext)
      }
      generateInFlightRef.current = false
      generationSeedRef.current = null
      setGenerating(false)
    }
    // Why: eligibility refreshes while the dialog is open; only seed fields
    // once per branch so late refreshes do not overwrite user edits.
    initializedFromEligibilityRef.current = initializationKey
    setInitializedEligibilityKey(initializationKey)
    autoGeneratedForKeyRef.current = null
    restoredExternalGenerationSeedRef.current = null
    fieldRevisionsRef.current = createInitialPullRequestFieldRevisions()
    baseEditedByUserRef.current = false
    syncedDefaultBaseRef.current = resolvedDefaultBaseRef || null
    setBase(resolvedDefaultBaseRef)
    setTitle(resolveCreateReviewDraftTitle({ branch, eligibilityTitle: eligibility.title }))
    setBody(eligibility.body ?? '')
    setDraft(resolvedPrDefaults.draft)
    setBaseQuery('')
    setBaseResults([])
    setBaseSearchError(null)
    setGenerateError(null)
  }, [
    autoGeneratedForKeyRef,
    baseEditedByUserRef,
    branch,
    currentEligibilityKey,
    eligibility,
    fieldRevisionsRef,
    generateInFlightRef,
    generationRequestIdRef,
    generationSeedRef,
    hasExternalGeneration,
    initializedFromEligibilityRef,
    open,
    repoId,
    resolvedDefaultBaseRef,
    resolvedPrDefaults.draft,
    restoredExternalGenerationSeedRef,
    retainDraftWhenClosed,
    setBase,
    setBaseQuery,
    setBaseResults,
    setBaseSearchError,
    setBody,
    setDraft,
    setGenerateError,
    setGenerating,
    setInitializedEligibilityKey,
    setTitle,
    syncedDefaultBaseRef,
    worktreeId,
    worktreePath
  ])

  const externalGenerationSeedRestoreKey = generation?.seedRestoreKey
  const externalGenerationSeed = generation?.seed
  const externalGenerationSeedFieldRevisions = generation?.seedFieldRevisions
  const onExternalGenerationSeedRestored = generation?.onSeedRestored

  useEffect(() => {
    if (
      !open ||
      !externalGenerationSeedRestoreKey ||
      !externalGenerationSeed ||
      !externalGenerationSeedFieldRevisions ||
      !initializedFromEligibilityRef.current ||
      restoredExternalGenerationSeedRef.current === externalGenerationSeedRestoreKey
    ) {
      return
    }
    // Why: external generation can survive component unmounts; restoring the
    // request seed keeps revision guards meaningful after the composer remounts.
    restoredExternalGenerationSeedRef.current = externalGenerationSeedRestoreKey
    fieldRevisionsRef.current = { ...externalGenerationSeedFieldRevisions }
    baseEditedByUserRef.current = true
    setBase(stripBaseRef(externalGenerationSeed.base))
    setTitle(externalGenerationSeed.title)
    setBody(externalGenerationSeed.body)
    setDraft(externalGenerationSeed.draft)
    setBaseQuery('')
    setBaseResults([])
    setBaseSearchError(null)
    onExternalGenerationSeedRestored?.(externalGenerationSeedRestoreKey)
  }, [
    baseEditedByUserRef,
    externalGenerationSeed,
    externalGenerationSeedFieldRevisions,
    externalGenerationSeedRestoreKey,
    fieldRevisionsRef,
    initializedFromEligibilityRef,
    onExternalGenerationSeedRestored,
    open,
    restoredExternalGenerationSeedRef,
    setBase,
    setBaseQuery,
    setBaseResults,
    setBaseSearchError,
    setBody,
    setDraft,
    setTitle
  ])

  useEffect(() => {
    if (
      !open ||
      !eligibility ||
      !initializedFromEligibilityRef.current ||
      !resolvedDefaultBaseRef
    ) {
      return
    }
    if (syncedDefaultBaseRef.current === resolvedDefaultBaseRef) {
      return
    }
    syncedDefaultBaseRef.current = resolvedDefaultBaseRef
    if (baseEditedByUserRef.current) {
      return
    }
    // Why: the Source Control compare-base picker can change the intended
    // review target while generation is in flight; bump the revision so stale
    // generated details cannot retarget an untouched base back to the old ref.
    markFieldDirty('base')
    setBase(resolvedDefaultBaseRef)
    setBaseQuery('')
    setBaseResults([])
    setBaseSearchError(null)
  }, [
    baseEditedByUserRef,
    eligibility,
    initializedFromEligibilityRef,
    markFieldDirty,
    open,
    resolvedDefaultBaseRef,
    setBase,
    setBaseQuery,
    setBaseResults,
    setBaseSearchError,
    syncedDefaultBaseRef
  ])
}
