import { useCallback, useRef, useState } from 'react'
import {
  DEFAULT_SOURCE_CONTROL_AI_PR_CREATION_DEFAULTS,
  resolveSourceControlAiForOperation
} from '../../../../shared/source-control-ai'
import type {
  PullRequestFieldName,
  PullRequestFieldRevisions
} from '@/store/slices/pull-request-generation'
import {
  resolveCreateReviewDefaultBaseRef,
  stripBaseRef
} from './create-pull-request-base-ref-normalization'
import {
  createInitialPullRequestFieldRevisions,
  type GenerationSeed,
  type PullRequestDraftFields,
  type UseCreatePullRequestDialogFieldsOptions
} from './create-pull-request-dialog-field-model'
import { useCreatePullRequestFieldSeeding } from './use-create-pull-request-field-seeding'
import { useCreatePullRequestBaseRefDiscovery } from './use-create-pull-request-base-ref-discovery'
import { useCreatePullRequestFieldGeneration } from './use-create-pull-request-field-generation'

export function useCreatePullRequestDialogFields({
  open,
  repoId,
  worktreeId,
  worktreePath,
  branch,
  eligibility,
  currentBaseRef,
  repo,
  settings,
  submitting,
  prCreationDefaults,
  sourceControlAiActionsVisible = true,
  retainDraftWhenClosed = false,
  onBranchChangedByGeneration,
  generation
}: UseCreatePullRequestDialogFieldsOptions) {
  const resolvedPullRequestAi = settings
    ? resolveSourceControlAiForOperation({
        settings,
        repo,
        operation: 'pullRequest'
      })
    : null
  const resolvedPrDefaults = {
    ...DEFAULT_SOURCE_CONTROL_AI_PR_CREATION_DEFAULTS,
    ...prCreationDefaults
  }
  const initializedFromEligibilityRef = useRef<string | null>(null)
  const [initializedEligibilityKey, setInitializedEligibilityKey] = useState<string | null>(null)
  const syncedDefaultBaseRef = useRef<string | null>(null)
  const baseEditedByUserRef = useRef(false)
  const autoGeneratedForKeyRef = useRef<string | null>(null)
  const generateInFlightRef = useRef(false)
  const generationRequestIdRef = useRef(0)
  const generationSeedRef = useRef<GenerationSeed | null>(null)
  const restoredExternalGenerationSeedRef = useRef<string | null>(null)
  const fieldRevisionsRef = useRef<PullRequestFieldRevisions>(
    createInitialPullRequestFieldRevisions()
  )
  const [base, setBase] = useState('')
  const [title, setTitle] = useState('')
  const [body, setBody] = useState('')
  const [draft, setDraft] = useState(false)
  const [baseQuery, setBaseQuery] = useState('')
  const [baseResults, setBaseResults] = useState<string[]>([])
  // Why: lets the picker withhold "no branches match" until a search settles, so
  // the debounce and an SSH round-trip can't read as an observed absence.
  const [baseSearchPending, setBaseSearchPending] = useState(false)
  const [baseSearchError, setBaseSearchError] = useState<string | null>(null)
  const [generating, setGenerating] = useState(false)
  const [generateError, setGenerateError] = useState<string | null>(null)
  const hasExternalGeneration = Boolean(generation)
  const currentEligibilityKey =
    open && eligibility ? `${repoId}:${worktreeId ?? worktreePath}:${branch}` : null
  const resolvedDefaultBaseRef = resolveCreateReviewDefaultBaseRef({
    currentBaseRef,
    eligibilityDefaultBaseRef: eligibility?.defaultBaseRef
  })

  const markFieldDirty = useCallback((field: PullRequestFieldName): void => {
    fieldRevisionsRef.current = {
      ...fieldRevisionsRef.current,
      [field]: fieldRevisionsRef.current[field] + 1
    }
  }, [])

  const setUserBase = useCallback(
    (value: string): void => {
      baseEditedByUserRef.current = true
      markFieldDirty('base')
      setBase(value)
    },
    [markFieldDirty]
  )
  const setUserTitle = useCallback(
    (value: string): void => {
      markFieldDirty('title')
      setTitle(value)
    },
    [markFieldDirty]
  )
  const setUserBody = useCallback(
    (value: string): void => {
      markFieldDirty('body')
      setBody(value)
    },
    [markFieldDirty]
  )
  const setUserDraft = useCallback(
    (value: boolean): void => {
      markFieldDirty('draft')
      setDraft(value)
    },
    [markFieldDirty]
  )

  const applyGeneratedFields = useCallback(
    (
      fields: PullRequestDraftFields,
      seedRevisions: PullRequestFieldRevisions
    ): PullRequestDraftFields => {
      const currentRevisions = fieldRevisionsRef.current
      const nextFields = { base, title, body, draft }
      // Why: AI generation runs asynchronously; only fields untouched since
      // the request started are safe to replace with generated output.
      if (currentRevisions.base === seedRevisions.base) {
        nextFields.base = stripBaseRef(fields.base)
        setBase(nextFields.base)
        setBaseQuery('')
        setBaseResults([])
      }
      if (currentRevisions.title === seedRevisions.title) {
        nextFields.title = fields.title
        setTitle(fields.title)
      }
      if (currentRevisions.body === seedRevisions.body) {
        nextFields.body = fields.body
        setBody(fields.body)
      }
      if (currentRevisions.draft === seedRevisions.draft) {
        nextFields.draft = fields.draft
        setDraft(fields.draft)
      }
      return nextFields
    },
    [base, body, draft, title]
  )

  useCreatePullRequestFieldSeeding({
    open,
    repoId,
    worktreeId,
    worktreePath,
    branch,
    eligibility,
    hasExternalGeneration,
    retainDraftWhenClosed,
    currentEligibilityKey,
    resolvedDefaultBaseRef,
    resolvedPrDefaults,
    generation,
    markFieldDirty,
    initializedFromEligibilityRef,
    syncedDefaultBaseRef,
    baseEditedByUserRef,
    autoGeneratedForKeyRef,
    generateInFlightRef,
    generationRequestIdRef,
    generationSeedRef,
    restoredExternalGenerationSeedRef,
    fieldRevisionsRef,
    setInitializedEligibilityKey,
    setBase,
    setTitle,
    setBody,
    setDraft,
    setBaseQuery,
    setBaseResults,
    setBaseSearchError,
    setGenerating,
    setGenerateError
  })

  const repoDefaultBaseRef = useCreatePullRequestBaseRefDiscovery({
    open,
    repoId,
    settings,
    base,
    baseQuery,
    setBase,
    setBaseResults,
    setBaseSearchPending,
    setBaseSearchError
  })

  const {
    effectiveGenerating,
    effectiveGenerateError,
    generateDisabled,
    generateDisabledReason,
    handleGenerate,
    handleCancelGenerate
  } = useCreatePullRequestFieldGeneration({
    open,
    submitting,
    resolvedPullRequestAi,
    base,
    title,
    body,
    draft,
    worktreeId,
    worktreePath,
    settings,
    eligibility,
    resolvedPrDefaults,
    generation,
    onBranchChangedByGeneration,
    applyGeneratedFields,
    generating,
    generateError,
    setGenerating,
    setGenerateError,
    initializedFromEligibilityRef,
    autoGeneratedForKeyRef,
    generateInFlightRef,
    generationRequestIdRef,
    generationSeedRef,
    fieldRevisionsRef
  })

  return {
    aiGenerationEnabled: sourceControlAiActionsVisible && resolvedPullRequestAi?.ok === true,
    initializedFromEligibility:
      currentEligibilityKey !== null && initializedEligibilityKey === currentEligibilityKey,
    base,
    setBase: setUserBase,
    title,
    setTitle: setUserTitle,
    body,
    setBody: setUserBody,
    draft,
    setDraft: setUserDraft,
    stackedCreationSupported: eligibility?.stackedCreationSupported === true,
    repoDefaultBaseRef,
    fieldRevisions: fieldRevisionsRef.current,
    applyGeneratedFields,
    baseQuery,
    setBaseQuery,
    baseResults,
    setBaseResults,
    baseSearchPending,
    baseSearchError,
    generating: effectiveGenerating,
    generateError: effectiveGenerateError,
    generateDisabled,
    generateDisabledReason,
    handleGenerate,
    handleCancelGenerate
  }
}
