import { useTerminalPaneStoreActions } from './use-terminal-pane-store-actions'
import { useTerminalPaneLifecycle } from './use-terminal-pane-lifecycle'
import type { TerminalPaneCloseController } from './use-terminal-pane-close-actions'

export function useTerminalPaneLifecycleStage(controller: TerminalPaneCloseController): void {
  const {
    clearExitedPanePtyLayoutBinding,
    clearExitedPanePtyLayoutBindingForLeaf,
    clearRuntimePaneTitle,
    clearTabPtyId,
    clearTerminalPaneUnread,
    clearTerminalTabUnread,
    clearWorktreeUnread,
    containerRef,
    cwd,
    dispatchNotification,
    effectiveMacOptionAsAlt,
    handleExternalPaneDrop,
    initialLayoutRef,
    isActive,
    isActiveRef,
    isRendererVisible,
    isVisibleRef,
    issueCommandSplit,
    macOptionAsAltRef,
    managerRef,
    markTerminalPaneUnread,
    markTerminalTabUnread,
    markWorktreeUnread,
    onAgentExitedRef,
    onPtyErrorClearedRef,
    onPtyErrorRef,
    onPtyExitRef,
    onPtyRecoveryStateRef,
    paneCwdRef,
    paneFontSizesRef,
    paneKittyKeyboardModesRef,
    paneLastThemeModeRef,
    paneMode2031Ref,
    panePtyBindingsRef,
    paneTitlesRef,
    paneTransportsRef,
    persistLayoutSnapshot,
    replayingPanesRef,
    requestOpenLinksInAppPreference,
    requestTerminalLinkAction,
    settleTabStartupCommand,
    resolveExternalPaneDropTarget,
    setCacheTimerStartedAt,
    setExpandedPane,
    setPaneCount,
    setPaneLayoutRevision,
    setPaneTitles,
    setRenamingPaneId,
    setRuntimePaneTitle,
    setTabCanExpandPane,
    setTabPaneExpanded,
    settings,
    settingsRef,
    setupSplit,
    showRestoredSessionBanner,
    startup,
    syncExpandedLayout,
    syncPanePtyLayoutBinding,
    syncPanePtyLayoutBindingForLeaf,
    systemPrefersDark,
    tabId,
    updateTabPtyId,
    updateTabTitle,
    worktreeId,
    expandedStyleSnapshotRef,
    getTabWideAgentHintLeafIdRef,
    handlePaneProcessDied
  } = controller
  const { consumeSuppressedPtyExit, isPtyShutdownPending } = useTerminalPaneStoreActions()

  useTerminalPaneLifecycle({
    tabId,
    worktreeId,
    cwd,
    startup,
    setupSplit,
    issueCommandSplit,
    isActive,
    isVisible: isRendererVisible,
    systemPrefersDark,
    settings,
    settingsRef,
    requestOpenLinksInAppPreference,
    requestTerminalLinkAction,
    effectiveMacOptionAsAlt,
    effectiveMacOptionAsAltRef: macOptionAsAltRef,
    initialLayoutRef,
    managerRef,
    getTabWideAgentHintLeafId: () => getTabWideAgentHintLeafIdRef.current(),
    containerRef,
    expandedStyleSnapshotRef,
    paneFontSizesRef,
    paneTransportsRef,
    paneCwdRef,
    paneMode2031Ref,
    paneKittyKeyboardModesRef,
    paneLastThemeModeRef,
    panePtyBindingsRef,
    replayingPanesRef,
    isActiveRef,
    isVisibleRef,
    onPtyExitRef,
    onAgentExitedRef,
    onPtyErrorRef,
    onPtyErrorClearedRef,
    onPaneProcessDied: handlePaneProcessDied,
    onPtyRecoveryStateRef,
    clearTabPtyId,
    consumeSuppressedPtyExit,
    isPtyShutdownPending,
    updateTabTitle,
    setRuntimePaneTitle,
    clearRuntimePaneTitle,
    updateTabPtyId,
    markWorktreeUnread,
    markTerminalTabUnread,
    markTerminalPaneUnread,
    clearWorktreeUnread,
    clearTerminalTabUnread,
    clearTerminalPaneUnread,
    onShowSessionRestoredBanner: showRestoredSessionBanner,
    dispatchNotification,
    setCacheTimerStartedAt,
    syncPanePtyLayoutBinding,
    syncPanePtyLayoutBindingForLeaf,
    clearExitedPanePtyLayoutBinding,
    clearExitedPanePtyLayoutBindingForLeaf,
    onStartupBound: settleTabStartupCommand,
    setTabPaneExpanded,
    setTabCanExpandPane,
    setExpandedPane,
    syncExpandedLayout,
    persistLayoutSnapshot,
    setPaneTitles,
    paneTitlesRef,
    setRenamingPaneId,
    setPaneCount,
    setPaneLayoutRevision,
    resolveExternalPaneDropTarget,
    onExternalPaneDrop: handleExternalPaneDrop
  })
}
